lt:
  oauth2:
    jwt:
      signing-key: mykey
      token-store-type: redis

server:
  port: 2000

spring:
  application:
    name: lt-auth
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3308/micro_services?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

eureka:
  client:
    service-url:
      defaultZone: http://me:1234@localhost:1000/eureka
    registry-fetch-interval-seconds: 10